"""
Asset model — represents any uploaded image or generated video stored in GCS.

Lifecycle (mirrors RateRail's Document pipeline for user uploads):
    UPLOADED → SCANNING → SCAN_PASSED → READY    (clean path)
    UPLOADED → SCANNING → SCAN_FAILED → QUARANTINED (infected)

For internally generated assets (videos we produced) we skip the scan
and create the row directly with status=READY and bucket=clean.
"""

import uuid

from django.db import models

from core.models import TimestampedModel


class AssetKind(models.TextChoices):
    SUBJECT_PHOTO = 'subject_photo', 'Subject Photo'   # user-uploaded reference photo of pet/person
    REFERENCE_FRAME = 'reference_frame', 'Reference Frame'  # processed/curated reference for video gen
    GENERATED_VIDEO = 'generated_video', 'Generated Video'  # our output
    GENERATED_THUMBNAIL = 'generated_thumbnail', 'Generated Thumbnail'
    AUDIO = 'audio', 'Audio'  # voiceover, music


class AssetStatus(models.TextChoices):
    UPLOADED = 'uploaded', 'Uploaded (awaiting scan)'
    SCANNING = 'scanning', 'Scanning'
    SCAN_PASSED = 'scan_passed', 'Scan passed'
    SCAN_FAILED = 'scan_failed', 'Scan failed (quarantined)'
    READY = 'ready', 'Ready'
    QUARANTINED = 'quarantined', 'Quarantined'
    DELETED = 'deleted', 'Deleted'


class Asset(TimestampedModel):
    """
    A single file in GCS. Either uploaded by a user or generated by us.
    """
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, db_index=True)
    organization = models.ForeignKey(
        'orgs.Organization', on_delete=models.CASCADE, related_name='assets'
    )
    uploaded_by = models.ForeignKey(
        'users.CustomUser', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='uploaded_assets',
    )

    kind = models.CharField(max_length=30, choices=AssetKind.choices)
    status = models.CharField(max_length=20, choices=AssetStatus.choices, default=AssetStatus.UPLOADED)

    # GCS location
    bucket = models.CharField(max_length=200)        # e.g. critter-clean / critter-quarantine
    object_key = models.CharField(max_length=500)    # path within the bucket

    # File metadata
    original_filename = models.CharField(max_length=255, blank=True)
    content_type = models.CharField(max_length=100, blank=True)
    size_bytes = models.BigIntegerField(default=0)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    duration_seconds = models.FloatField(null=True, blank=True)  # videos / audio

    # Scan results
    scan_started_at = models.DateTimeField(null=True, blank=True)
    scan_completed_at = models.DateTimeField(null=True, blank=True)
    scan_result = models.CharField(max_length=200, blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['organization', 'kind']),
            models.Index(fields=['organization', 'status']),
            models.Index(fields=['kind', 'status', 'created_at']),
        ]
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.get_kind_display()} {self.uuid} ({self.get_status_display()})'

    def gcs_uri(self):
        return f'gs://{self.bucket}/{self.object_key}'

    def public_url(self):
        return f'https://storage.googleapis.com/{self.bucket}/{self.object_key}'

    def signed_url(self, expires_seconds=3600):
        """Return a short-lived signed URL (1h default)."""
        from .storage import generate_signed_url
        return generate_signed_url(self.bucket, self.object_key, expires_seconds)
