# Generated by Django 5.1.3 on 2026-04-21 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cover_emoji', models.CharField(blank=True, max_length=8)),
                ('shot_style', models.CharField(choices=[('cinematic', 'Cinematic'), ('handheld', 'Handheld / iPhone'), ('macro', 'Macro / close-up'), ('overhead', 'Overhead'), ('pov', 'POV'), ('studio', 'Studio')], default='handheld', max_length=20)),
                ('music_vibe', models.CharField(choices=[('asmr_ambient', 'ASMR / ambient'), ('lofi', 'Lo-fi'), ('upbeat', 'Upbeat'), ('emotional', 'Emotional / cinematic'), ('trending', 'Trending audio (substitute later)'), ('silent', 'Silent / dialogue only')], default='lofi', max_length=20)),
                ('prompt_template', models.TextField(help_text='Template with {subject_description}, {subject_name}, {scenario}, {detail} placeholders')),
                ('caption_template', models.TextField(blank=True)),
                ('default_scenarios', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='orgs.organization')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='themes_them_organiz_a89e21_idx'), models.Index(fields=['is_featured', 'is_active'], name='themes_them_is_feat_321af7_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
