# Generated by Django 5.1.3 on 2026-04-21 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(choices=[('subject_photo', 'Subject Photo'), ('reference_frame', 'Reference Frame'), ('generated_video', 'Generated Video'), ('generated_thumbnail', 'Generated Thumbnail'), ('audio', 'Audio')], max_length=30)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded (awaiting scan)'), ('scanning', 'Scanning'), ('scan_passed', 'Scan passed'), ('scan_failed', 'Scan failed (quarantined)'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('deleted', 'Deleted')], default='uploaded', max_length=20)),
                ('bucket', models.CharField(max_length=200)),
                ('object_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_result', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
