# Generated by Django 5.1.3 on 2026-04-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'kind'], name='assets_asse_organiz_990617_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'status'], name='assets_asse_organiz_ad90f0_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['kind', 'status', 'created_at'], name='assets_asse_kind_5aa2d0_idx'),
        ),
    ]
