# Generated by Django 5.1.3 on 2026-04-21 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('pet', 'Pet'), ('person', 'Person'), ('object', 'Object')], default='pet', max_length=10)),
                ('species', models.CharField(blank=True, choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('reptile', 'Reptile'), ('other', 'Other')], max_length=20)),
                ('auto_description', models.TextField(blank=True)),
                ('user_description', models.TextField(blank=True, help_text='Optional override / addendum')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='The "best" reference photo — used as the canonical character image')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
