# Generated by Django 5.1.3 on 2026-04-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
        ('orgs', '0002_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='subjectphoto',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_photo_links', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='subjectphoto',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_photos', to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['organization', 'is_archived'], name='subjects_su_organiz_a4bef1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['organization', 'kind'], name='subjects_su_organiz_b97361_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectphoto',
            index=models.Index(fields=['subject', 'order'], name='subjects_su_subject_f3a570_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectphoto',
            unique_together={('subject', 'asset')},
        ),
    ]
