# Generated by Django 5.1.3 on 2026-04-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user', 'created_at'], name='analytics_r_user_id_d692c8_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['path', 'created_at'], name='analytics_r_path_e109ad_idx'),
        ),
    ]
