# Generated by Django 5.1.3 on 2026-04-21 04:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('provider', models.CharField(choices=[('veo', 'Veo 3 (Vertex AI)'), ('runway', 'Runway Gen-4')], default='veo', max_length=10)),
                ('aspect_ratio', models.CharField(default='9:16', max_length=8)),
                ('duration_seconds', models.IntegerField(default=8)),
                ('extra_detail', models.TextField(blank=True)),
                ('expand_prompts_with_claude', models.BooleanField(default=True)),
                ('generate_captions', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('scenario', models.CharField(blank=True, help_text='Per-video twist (e.g. "tiny pancakes", "the vacuum cleaner")', max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('rendered_prompt', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('rq_job_id', models.CharField(blank=True, max_length=64)),
                ('video_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_outputs', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
