# Generated by Django 5.1.3 on 2026-04-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generations', '0001_initial'),
        ('orgs', '0001_initial'),
        ('subjects', '0001_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_batches', to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_batches', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_batches', to='themes.theme'),
        ),
        migrations.AddField(
            model_name='generation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='generations.generationbatch'),
        ),
        migrations.AddIndex(
            model_name='generationbatch',
            index=models.Index(fields=['organization', 'status'], name='generations_organiz_0b393f_idx'),
        ),
        migrations.AddIndex(
            model_name='generationbatch',
            index=models.Index(fields=['subject', 'status'], name='generations_subject_fb4ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['batch', 'status'], name='generations_batch_i_42dc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status', 'created_at'], name='generations_status_0a5645_idx'),
        ),
    ]
