# Generated by Django 5.1.3 on 2026-04-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationbatch',
            name='provider',
            field=models.CharField(choices=[('veo_31_lite', 'Veo 3.1 Lite (cheapest, fastest)'), ('veo_31_fast', 'Veo 3.1 Fast (balanced)'), ('veo_31', 'Veo 3.1 Standard (best quality)'), ('veo_30_fast', 'Veo 3.0 Fast'), ('veo_30', 'Veo 3.0 Standard'), ('runway', 'Runway Gen-4 (best character consistency)')], default='veo_31_lite', max_length=20),
        ),
    ]
