# Generated by Django 5.1.3 on 2026-04-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
        ('generations', '0003_alter_generationbatch_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='video_asset_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_raw_outputs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='music_fade_in_seconds',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='music_fade_out_seconds',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='music_start_offset_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='music_track',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'audio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_music_in_batches', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='music_volume',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='original_audio_fade_in_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='original_audio_fade_out_seconds',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='original_audio_volume',
            field=models.FloatField(default=0.7),
        ),
    ]
