# Generated by Django 5.1.3 on 2026-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0004_generation_video_asset_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationbatch',
            name='use_photo_background',
            field=models.BooleanField(default=True),
        ),
    ]
