# Generated by Django 5.1.3 on 2026-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0005_generationbatch_use_photo_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationbatch',
            name='person_generation',
            field=models.CharField(choices=[('auto', 'Auto (based on subject kind)'), ('dont_allow', 'Strict — no humans / faces in videos'), ('allow_adult', 'Allow adult humans (no minors)'), ('allow_all', 'Allow everyone (least restrictive)')], default='auto', max_length=20),
        ),
    ]
