# Generated by Django 5.1.3 on 2026-04-21 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0006_generationbatch_person_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('original_audio_volume', models.FloatField(default=1.0)),
                ('original_audio_fade_in_seconds', models.FloatField(default=0.0)),
                ('original_audio_fade_out_seconds', models.FloatField(default=0.0)),
                ('music_volume', models.FloatField(default=0.5)),
                ('music_start_offset_seconds', models.FloatField(default=0.0)),
                ('music_fade_in_seconds', models.FloatField(default=0.0)),
                ('music_fade_out_seconds', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
