# Generated by Django 5.1.3 on 2026-04-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
        ('generations', '0007_audiomix'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='stories.storyscene'),
        ),
        migrations.AddField(
            model_name='generation',
            name='take_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='variations_per_scenario',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='generation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='generations.generationbatch'),
        ),
        migrations.AlterField(
            model_name='generationbatch',
            name='person_generation',
            field=models.CharField(choices=[('allow_adult', 'Allow people (recommended) — Veo decides if any are needed; no minors'), ('dont_allow', 'No people in videos — both Veo + prompt enforce'), ('allow_all', 'Allow everyone, including kids (rare)'), ('auto', '(legacy) Auto')], default='allow_adult', max_length=20),
        ),
        migrations.AlterField(
            model_name='generationbatch',
            name='provider',
            field=models.CharField(choices=[('veo_31_lite', 'Veo 3.1 Lite (cheapest, fastest)'), ('veo_31_fast', 'Veo 3.1 Fast (balanced)'), ('veo_31', 'Veo 3.1 Standard (best quality)'), ('veo_30_fast', 'Veo 3.0 Fast'), ('veo_30', 'Veo 3.0 Standard'), ('runway_gen3', 'Runway Gen-3 Alpha Turbo (cheap legacy, image-to-video)'), ('runway_gen4', 'Runway Gen-4 Turbo (fastest image-to-video)'), ('runway_gen4_5', 'Runway Gen-4.5 (state-of-the-art, text+image to video)'), ('kling_21', 'Kling 2.1 Master (cinematic, premium)'), ('runway', '(legacy) Runway')], default='veo_31_lite', max_length=20),
        ),
        migrations.AddField(
            model_name='audiomix',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='generations.generation'),
        ),
        migrations.AddField(
            model_name='audiomix',
            name='music_track',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'audio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_mixes', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='audiomix',
            name='output_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_audio_mix_output', to='assets.asset'),
        ),
        migrations.AddIndex(
            model_name='audiomix',
            index=models.Index(fields=['generation', '-created_at'], name='generations_generat_5aea6a_idx'),
        ),
    ]
