# Generated by Django 5.1.3 on 2026-04-21 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
        ('generations', '0007_audiomix'),
        ('orgs', '0002_initial'),
        ('subjects', '0002_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('concept', models.TextField(help_text='The one-line pitch Claude uses to plan the scenes. E.g. "Mr Kitty discovers Antarctica and befriends a penguin."')),
                ('provider', models.CharField(default='veo_31_lite', max_length=20)),
                ('aspect_ratio', models.CharField(default='9:16', max_length=8)),
                ('target_duration_seconds', models.IntegerField(default=30, help_text='Total video length target')),
                ('per_scene_duration_seconds', models.IntegerField(choices=[(4, '4s'), (6, '6s'), (8, '8s')], default=8)),
                ('extra_detail', models.TextField(blank=True)),
                ('expand_prompts_with_claude', models.BooleanField(default=True)),
                ('generate_captions', models.BooleanField(default=False)),
                ('use_photo_background', models.BooleanField(default=True)),
                ('person_generation', models.CharField(default='allow_adult', max_length=20)),
                ('original_audio_volume', models.FloatField(default=0.7)),
                ('original_audio_fade_in_seconds', models.FloatField(default=0.0)),
                ('original_audio_fade_out_seconds', models.FloatField(default=0.5)),
                ('music_volume', models.FloatField(default=0.5)),
                ('music_start_offset_seconds', models.FloatField(default=0.0)),
                ('music_fade_in_seconds', models.FloatField(default=0.5)),
                ('music_fade_out_seconds', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning scenes…'), ('planned', 'Planned, not generated'), ('generating', 'Generating takes…'), ('takes_ready', 'Takes ready, waiting for picks'), ('stitching', 'Stitching final video…'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('final_video_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_finals', to='assets.asset')),
                ('music_track', models.ForeignKey(blank=True, limit_choices_to={'kind': 'audio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_stories', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='orgs.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='subjects.subject')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='themes.theme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(help_text='Short label, e.g. "Mr Kitty steps off the spaceship"', max_length=200)),
                ('prompt', models.TextField(help_text='The actual Veo prompt for this scene (before auto-describe/Claude expansion)')),
                ('duration_seconds', models.IntegerField(choices=[(4, '4s'), (6, '6s'), (8, '8s')], default=8)),
                ('desired_takes', models.IntegerField(default=1, help_text='How many variations to generate for this scene')),
                ('transition_out', models.CharField(choices=[('cut', 'Hard cut'), ('crossfade', 'Crossfade (0.5s)'), ('fade_black', 'Fade through black (0.5s)')], default='crossfade', help_text='Transition TO the next scene (ignored on the last scene)', max_length=20)),
                ('chosen_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_in_scenes', to='generations.generation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.storyproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='storyproject',
            index=models.Index(fields=['organization', 'status'], name='stories_sto_organiz_267c95_idx'),
        ),
        migrations.AddIndex(
            model_name='storyproject',
            index=models.Index(fields=['subject'], name='stories_sto_subject_f533ec_idx'),
        ),
        migrations.AddIndex(
            model_name='storyscene',
            index=models.Index(fields=['project', 'order'], name='stories_sto_project_5ef9fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storyscene',
            unique_together={('project', 'order')},
        ),
    ]
